version: '3.8'

services:
  react-app:
    build: .
    image: benphamdev/personal-portfolio-react:latest
    container_name: react-app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    working_dir: /app